version: 2
updates:
  # Enable version updates for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "21:12"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 10
    reviewers:
      - "MaBoNi"
    assignees:
      - "MaBoNi"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "21:12"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 10
    reviewers:
      - "MaBoNi"
    assignees:
      - "MaBoNi"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
